name: Deploy On s3

on:
    workflow_dispatch : {}
    push:
      branches:
      - main
      - master
jobs:
  build:
    name: Compile React App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install Deps 🤖
        run : npm i

      - name: "Compile App"
        run: npm run build

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy on s3
        run: aws s3 sync build/ s3://${{ vars.AWS_BUCKET_NAME}}
